services:
  node:
    build: .
    ports:
      - "8003:8080"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    command: gunicorn --bind 0.0.0.0:8080 --workers 4 --threads 2 app:app
    restart: unless-stopped
